name: pdf_viewer_plugin_example
description: Demonstrates how to use the pdf_viewer_plugin plugin.
version: 1.0.0+2
dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.11
  http:
  pdf_viewer_plugin:
    path: ../
  uuid: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/